images:
  tproxyRegistry: docker.io/horodchukanton
  pullPolicy: IfNotPresent
  mitmproxy: tproxy-mitmproxy:latest
  initFirewall: tproxy-firewall:latest
  injectorWebhook: tproxy-webhook:latest

tproxy:
  useRBAC: false
  hostPort: 8080
  addStandardModeProxy: false
  outboundLogEndpoint: "https://gl-ss-testenv-api.int.testenv.gl-k8s.com/api/v1.0/outbound"
  # blockSvcCIDR: 10.11.240.0/20
  # allowDNS: 10.11.240.10
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

injector:
  # Namespace where webhook lives
  injectorNamespace: "injector"
  controledNamespace: "injection"

  # True if you want to enable mitmproxy sidecar injection.
  enabled: true
  namespaceSelector:
     matchLabels:
       sidecar-injection: enabled
#  objectSelector:
#    matchLabels:
#      mitmproxy-sidecar-injector: enabled
  failurePolicy: Fail
