apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos-app-locked
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos-app
  template:
    metadata:
      annotations:
        "sidecar-injector-webhook.webhook.me/inject": enabled
      labels:
        app: centos-app
        variant: locked
    spec:
      containers:
        - name: app
          image: danisla/example-app:centos
          imagePullPolicy: IfNotPresent
