apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian-app-locked
#  annotations:
  labels:
    mitmproxy-sidecar-injector: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian-app
  template:
    metadata:
      labels:
        app: debian-app
        variant: locked
    spec:
      containers:
        - name: app
          image: danisla/example-app:debian
          imagePullPolicy: IfNotPresent
