apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian-app-locked-manual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian-app
  template:
    metadata:
      annotations:
      labels:
        app: debian-app
        variant: locked
    spec:
      containers:
        - name: app
          image: danisla/example-app:debian
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: ca-certs-debian
              mountPath: /etc/ssl/certs/
            - name: ca-certs-debian
              # Adding the cert to the /extra dir preserves it if update-ca-certificates is run after init.
              mountPath: /usr/local/share/ca-certificates/extra/
        - name: mitmproxy
          image: horodchukanton/tproxy-mitmproxy
          imagePullPolicy: Always
          tty: true
          securityContext:
            runAsGroup: 1337
            runAsNonRoot: true
            runAsUser: 1337
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - NET_ADMIN
              - NET_RAW
              drop:
              - ALL
          command:
            - mitmdump
            - '-p'
            - '1080'
            - '--mode'
            - 'transparent'
            - '--ssl-insecure'
            - '--showhost'
            - '--set'
            - 'confdir=/home/mitmproxy/.mitmproxy'
            - '--set'
            - 'stream-large-bodies=true'
            - '-s'
            - /opt/mitmproxy-scripts/mitm-script.py
          env:
            - name: "REMOTE_SERVER"
              value: "https://gl-ss-testenv-api.int.testenv.gl-k8s.com"
          volumeMounts:
            - name: mitmproxy-certs
              mountPath: /home/mitmproxy/.mitmproxy
            - name: app-data
              mountPath: /opt/mitmproxy-scripts/
      initContainers:
        - name: firewall-init
          image: horodchukanton/tproxy-firewall:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - name: firewall-rules
              mountPath: /tmp/firewall/
      volumes:
        - name: ca-certs-debian
          configMap:
            name: webhook-tproxy-root-certs
            items:
              - key: root-certs.crt
                path: ca-certificates.crt
        - name: mitmproxy-certs
          secret:
            secretName: webhook-tproxy-mitmproxy-certs
        - name: app-data
          configMap:
            name: webhook-tproxy-mitmproxy-configmap
            items:
              - key: mitm-script.py
                path: mitm-script.py
        - name: firewall-rules
          configMap:
           name: webhook-tproxy-init-firewall-configmap
           defaultMode: 0777
           items:
            - key: init-firewall.sh
              path: start.sh
