apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tproxy.fullname" . }}-injector-webhook-deployment
  namespace: {{ .Values.injector.injectorNamespace }}
  labels:
    app: {{ template "tproxy.name" . }}-injector
    component: sidecar-injector-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "tproxy.name" . }}-injector
  template:
    metadata:
      labels:
        app: {{ template "tproxy.name" . }}-injector
    spec:
      containers:
        - name: sidecar-injector
          image: {{ .Values.images.tproxyRegistry }}/{{ .Values.images.injectorWebhook }}
          imagePullPolicy: IfNotPresent
          args:
            - -sidecarCfgFile=/etc/webhook/config/sidecarconfig.yaml
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          env:
            # This is used to control inject status annotation for injector's webhook
            - name: RELEASE_NAME
              value: {{ .Release.Name }}
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-config
              mountPath: /etc/webhook/config
      volumes:
        - name: webhook-certs
          secret:
            secretName: tproxy-sidecar-injector-webhook-certs
        - name: webhook-config
          configMap:
            name: {{ template "tproxy.fullname" . }}-injector-webhook-configmap
            items:
              - key: sidecarconfig.yaml
                path: sidecarconfig.yaml
