{{- if .Values.tproxy.useRBAC }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tproxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "tproxy.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: tproxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "tproxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "tproxy.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: tproxy
subjects:
  - kind: ServiceAccount
    name: {{ template "tproxy.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "tproxy.fullname" . }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "tproxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "tproxy.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: tproxy
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps"]
    resourceNames:
      - {{ template "tproxy.fullname" . }}-mitmproxy-configmap
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - {{ template "tproxy.fullname" . }}-root-certs
    verbs: ["get", "list"]
{{- end }}
