apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tproxy.fullname" . }}-mitmproxy-configmap
  namespace: {{ .Values.injector.controledNamespace }}
  labels:
    app: "{{ template "tproxy.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: tproxy
data:
  mitm-script.py: |
{{ .Files.Get "config/mitm-script.py" | indent 4 }}
