apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tproxy.fullname" . }}-root-certs
  labels:
    app: {{ template "tproxy.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: tproxy
data:
  root-certs.crt: |-
    {{ range .Files.Lines "config/root-certs.crt" }}
    {{ . }}{{ end }}{{ range .Files.Lines "certs/mitmproxy-ca-cert.cer" }}
    {{ . }}{{ end }}